pages:
    resource: "@PagesBundle/Resources/config/routing.yml"
    prefix:   /

utilisateurs:
    resource: "@UtilisateursBundle/Resources/config/routing.yml"
    prefix:   /

restaurant:
    resource: "@RestaurantBundle/Resources/config/routing.yml"
    prefix:   /

