<?php

namespace Restaurant\RestaurantBundle\Repository;

/**
 * MediaRStRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRStRepository extends \Doctrine\ORM\EntityRepository {

}
