<?php

namespace Restaurant\RestaurantBundle\Repository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends \Doctrine\ORM\EntityRepository {

    public function findArray($array) {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->Where('u.id IN (:array)')
            ->setParameter('array', $array);
        return $qb->getQuery()->getResult();
    }

    public function byRestaur($restaur) {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.restaur = :restaur')
            ->orderBy('u.id')
            ->setParameter('restaur', $restaur);
        return $qb->getQuery()->getResult();
    }

}
