<?php

namespace Restaurant\RestaurantBundle\Repository;

/**
 * UtilisateursReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateursReservationRepository extends \Doctrine\ORM\EntityRepository
{
}
