parameters:
#    restaurant.example.class: Restaurant\RestaurantBundle\Example
services:
    tva:
          class: Restaurant\RestaurantBundle\Twig\Extension\TvaExtension
          tags:
            - { name: twig.extension }
    montantTva:
           class: Restaurant\RestaurantBundle\Twig\Extension\MontantTvaExtension
           tags:
             - { name: twig.extension }

    redirectionListener:
          class: Restaurant\RestaurantBundle\Listener\RedirectionListener
          arguments: [@service_container,@session]
          tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }